- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 28800 # DeltaV - 8 hours
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: UniformScrubsColorCybersun
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    # the purple glasses?
  innerClothingSkirt: UniformScrubsColorCybersun
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
