- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 14400 #4 hrs
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  - Paramedic # DeltaV - Add Paramedic access
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: UniformScrubsColorCybersun
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatCybersunWindbreaker
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    head: ClothingHeadHatSurgcapCybersun
  innerClothingSkirt: UniformScrubsColorCybersun
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
